### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by erikrikarddaniel** [erikrikarddaniel/pfitmap-nextflow#1]
* Collect a few (10-20) genomes in the form of faa.gz files (in `testdata/genomes`) 
* Collect a few hmm profiles (in `testdata/profiles`)

**Comment by GhadaNOUAIRIA** [comment]
done
8 NrdA subclass profiles
13 GCA*.faa.gz + 7 UBA*.faa.gz (symbolic links)

**Comment by erikrikarddaniel** [comment]
Use real files, not symlinks, but subset to positives plus some more.
