### ISSUE TITLE
Accept remote *and* local metadata files

### ISSUE THREAD

**Issue by erikrikarddaniel** [erikrikarddaniel/pfitmap-nextflow#13]
Nextflow can handle remote and local files in the same way by using the fromPath() method when constructing a channel. See e.g. https://github.com/nf-core/ampliseq: Channel.fromPath("${params.reference_database}"). If I understand it correctly, setting up the channel with a url will automatically download the remote file and make it available locally to the process. I think the process that creates the concatenated metadata file should therefore listen to two channels: One for the bacterial, one for the archaeal metadata files.

**Comment by GhadaNOUAIRIA** [comment]
Yes, it works with the url and nextflow downloads it automatically.

**Comment by GhadaNOUAIRIA** [comment]
change parameters names....

**Comment by GhadaNOUAIRIA** [comment]
The parameters names both in main.nf and test.config are 
gtdb_arc_metadata
gtdb_bac_metadata
so they are not depending on this 120/122, already.
I just changed the names of the files in testdata/arc122_metadata.tsv to testdata/arc_metadata.tsv (and so for bac).
