### ISSUE TITLE
`test.config` should be in the `conf` subdirectory

### ISSUE THREAD

**Issue by erikrikarddaniel** [erikrikarddaniel/pfitmap-nextflow#14]
We should have a `conf` directory with all config files except the main `nextflow.config`.

**Comment by erikrikarddaniel** [comment]
Currently, `-profile test` doesn't work. I get the following error:

```
WARN: Access to undefined parameter `inputgenomes` -- Initialise it to a default value eg. `params.inputgenomes = some_value`
Missing `fromPath` parameter
```

**Comment by GhadaNOUAIRIA** [comment]
what if you add -c test.config to your nextflow command?

**Comment by GhadaNOUAIRIA** [comment]
If it works with -c flag, maybe it's because the conf/test.config file is not included in the nextflow.config file?
you probably know it already but you can specify test.config in nextflow.config with :
includeConfig 'conf/test.config'

**Comment by GhadaNOUAIRIA** [comment]
According to nextflow documentation (section configuration), nextflow looks for ./nextflow.config, or nextflow.config in directory where the script is or ~/.nextflow/config. It does not look into subdirectories (so it does not look into conf/). 
So either I move conf/test.config to ./nextflow.config 
or I write ~/.nextflow/config where I specify for nextflow to look for config files in ./conf/.

PS: The way I configured the profile "test" is absolutely right. Because if I move test.config to ./nextflow.config, the profile test will run (with no -c flag).

So I have no idea how to fix in another way.

**Comment by erikrikarddaniel** [comment]
Den tors 23 apr. 2020 kl 10:23 skrev GhadaNOUAIRIA <notifications@github.com>:
>
> According to nextflow documentation (section configuration), nextflow looks for ./nextflow.config, or nextflow.config in directory where the script is or ~/.nextflow/config. It does not look into subdirectories (so it does not look into conf/).
> So either I move conf/test.config to ./nextflow.config
> or I write ~/.nextflow/config where I specify for nextflow to look for config files in ./conf/.
>
You're right; sorry for being stubborn before checking.

The way they do it in nf-core looks like this (nextflow.config):

profiles {
  awsbatch { includeConfig 'conf/awsbatch.config' }
  conda { process.conda = "$baseDir/environment.yml" }
  debug { process.beforeScript = 'echo $HOSTNAME' }
  docker {
    docker.enabled = true
    docker.temp = 'auto'
    env {
      JOBLIB_TEMP_FOLDER="/tmp"
    }
  }
  singularity { singularity.enabled = true }
  test { includeConfig 'conf/test.config' }
}

In test.config, they then don't have a profiles block (since they wrap
the include above), but instead just content like this:

params {
  config_profile_name = 'Test profile'
  config_profile_description = 'Minimal test dataset to check pipeline function'
  // Limit resources so that this can run on Travis
  max_cpus = 2
  max_memory = 6.GB
  max_time = 48.h
}

I think this is a rather nice way of doing it.

**Comment by GhadaNOUAIRIA** [comment]
I created nextflow.config and made the changes to test.config
Issue should be solved now
