### ISSUE TITLE
Sequence import

### ISSUE THREAD

**Issue by erikrikarddaniel** [erikrikarddaniel/pfitmap-nextflow#17]
1. Make sure that input faa file has sequences on one line. There's a macro in makefile.misc.
2. Make process that greps faa file for all *unique* accessions in result files. Use -C 1 and don't forget to pipe to `grep -v '^--'` to get rid of delimiter between hits.

**Comment by GhadaNOUAIRIA** [comment]
1. On branch pfTables; I wrote a new process to format all_genomes.faa, so that the sequences are on one line. I pushed the changes.
If you don't want this step as a separate process and you think it should be just a part of the fetchSequences step (point 2. in this issue), please tell me.

**Comment by erikrikarddaniel** [comment]
I hope we won't need this. I'm adding a fasta file option to `pf-classify.r` and if we don't run into memory problems, that should do it. We'll just have to duplicate the output channel from the process that creates the big fasta file. All in all, wait a bit with this.

**Comment by GhadaNOUAIRIA** [comment]
Ok. Anyway I'm out for a launch with Youssef since it's his birthday.

 I'll get back to reading/working on the application then 😊

**Comment by erikrikarddaniel** [comment]
Closing this, because `pf-classify.r` now takes a fasta file.
