### ISSUE TITLE
Parameters missing from help message

### ISSUE THREAD

**Issue by erikrikarddaniel** [erikrikarddaniel/pfitmap-nextflow#19]
There are currently only four documented parameters, all should be.

**Comment by GhadaNOUAIRIA** [comment]
Now help message describes 
7 mandatory args: inputgenome, gtdb_bac_metadata, gtdb_arc_metadata, profiles_hierarchy, hmm_mincov, bdsource and outputdir
2 non-mandatory: max_cpus (default = 2) and max_time (defautl = 10 days)
