### ISSUE TITLE
Export of feather files.

### ISSUE THREAD

**Issue by erikrikarddaniel** [erikrikarddaniel/pfitmap-nextflow#22]
If we're lucky this is just a matter of calling `pf-db2feather.r` with the sqlite database created by `pf-classify.r`.

**Comment by erikrikarddaniel** [comment]
I just checked the `pf-db2feather.r` script and it exports the `sequences` table if it's present in the sqlite database used as input.

**Comment by GhadaNOUAIRIA** [comment]
Running pf-db2feather.r, 
all packages are built successfully
It reads/connects to gtdb.pf.db
It writes accessions 
While writing taxa it get the Error: `by` can't contain join column `taxon` which is missing from LHS
Any idea how to fix it?

**Comment by erikrikarddaniel** [comment]
Which branch did you commit these changes to? I guessed `feather_export` but it doesn't have any process that fits and the `arc_metadata.tsv` file is missing from `testdata`.

**Comment by GhadaNOUAIRIA** [comment]
It is the same branch feather_export
I did not push this since you did not merge the last changes (error message for dbsource). I merged and pushed now.

**Comment by GhadaNOUAIRIA** [comment]
Error with pf-db2feather:
Occurs while trying to write taxa.feather : No column named taxon
Same error when trying to write domains: No column accto

In the script both these columns are only called under the condition where (opt$options$gtdb) is false (as the data in sql gtdb.db does not have these columns)

If I comment :
else {
   db %>% tbl('taxa') %>% semi_join(accessions %>% distinct(taxon), by = 'taxon') %>% collect() %>%
     write_feather(sprintf("%staxa.feather", opt$options$prefix))
}
.... then the script works and the output table taxa.pfitmap looks fine.

I don't know yet why the script do enter the "else" loop when the condition is false! Working on it.
