### ISSUE TITLE
--hmms param not documented

### ISSUE THREAD

**Issue by erikrikarddaniel** [erikrikarddaniel/pfitmap-nextflow#32]
`--hmms` is not in the help message.

**Comment by GhadaNOUAIRIA** [comment]
DOne

**Comment by GhadaNOUAIRIA** [comment]
commit 71936425604282c64a417616abb4c22c1d8e538a
changes to help message: parameter --hmm added and descrition of inputgenomes changed

**Comment by erikrikarddaniel** [comment]
You can close issues. Easiest is to just say: Fixed in NN and then press "Close and comment" (where NN is the commit id).
