### ISSUE TITLE
There are a lot of "gtdb" in the code

### ISSUE THREAD

**Issue by erikrikarddaniel** [erikrikarddaniel/pfitmap-nextflow#35]
I never thought of the workflow as GTDB specific and that one should provide a parameter to pass on to e.g. the classification. If that still holds, we should clean up and get rid of "gtdb" in names of files etc.

**Comment by GhadaNOUAIRIA** [comment]
Changing parameters names is easy to do. The structure itself of the parameters/processes is suited for the gtdb file structure; i.e.: we have metadata files separately for archaea and bacteria, pf-classification uses certain fields of these files....
Shall we provide a describtion for these input files according to the scripts requirements? 
If another db has one metadata file, we should allow the parameter to be empty (i.e: script should not fail if there is no arc_metadata input parameter and the process that uses it should be skipped).
I already though about providing a description of profiles_hierarchy file as it must have a standard format.

**Comment by erikrikarddaniel** [comment]
This issue is just a discussion point, so no need to do anything now. I actually think I need to edit myself: I probably did think of this workflow as GTDB specific, so maybe we just keep it as it is.
You raise issues that makes changing the workflow much more work than just changing some names, so I think we keep it as it is and make it more general only if needed.
**Please open an issue** regarding describing the `profiles_hierarchy` file! That's separate, and I'm closing this.
