### ISSUE TITLE
profile_hierarchy

### ISSUE THREAD

**Issue by GhadaNOUAIRIA** [erikrikarddaniel/pfitmap-nextflow#38]
We should make a description about the format of profiles_hierarchy.tsv with the requirements of our workflow.

**Comment by GhadaNOUAIRIA** [comment]
Should the description be in README file or in a separate one?

**Comment by erikrikarddaniel** [comment]
I think it would be good in the README.md plus a reference in the help message.

**Comment by GhadaNOUAIRIA** [comment]
Commit 1b1b70ba5d4c47db65e4716086d9da5fc67b273e
Please check the description for clarity/completeness

**Comment by erikrikarddaniel** [comment]
I think it would be better if it had an example, like:

```
profile nn nn
NrdA class NrdA
```

(Remember that you can enclose a section in three backticks to get it to render like code. Another thing is that it's tricky to get tabs in; if you copy and paste from somewhere it should work.)
