### ISSUE TITLE
New process: GTDB metadata required

### ISSUE THREAD

**Issue by erikrikarddaniel** [erikrikarddaniel/pfitmap-nextflow#6]
The `pf-classify.r` script requires a single file with GTDB metadata (provided to the script with the `--gtdbmetadata` parameter). The file should be a concatenation of the `ar122_metadata.tsv` and `bac120_metadata.tsv` files, but with only *one header line*. Files should be downloaded by the process.

**Comment by GhadaNOUAIRIA** [comment]
Done.
Tried it and it worked.
I'll push when I finish with the next process (running pf-classify.r)

**Comment by erikrikarddaniel** [comment]
Den ons 15 apr. 2020 kl 09:38 skrev GhadaNOUAIRIA <notifications@github.com
>:

> Done.
> Tried it and it worked.
> I'll push when I finish with the next process (running pf-classify.r)
>

I wouldn't wait until then.

**Comment by GhadaNOUAIRIA** [comment]
Sorry, didn't get the e-mail on time. Now I set a notification alarm for my gmails on the computer.
I pushed
