### ISSUE TITLE
Help message for params

### ISSUE THREAD

**Issue by erikrikarddaniel** [erikrikarddaniel/pfitmap-nextflow#7]
Check DL's main.nf from TARA project

**Comment by GhadaNOUAIRIA** [comment]
done
max_cpus, last_cpus and max_time may be added later (think about default values)

**Comment by erikrikarddaniel** [comment]
Den ons 15 apr. 2020 kl 23:26 skrev GhadaNOUAIRIA <notifications@github.com>:
>
> done
> max_cpus, last_cpus and max_time may be added later (think about default values)

We won't need "last_cpus", but the other two should be in at some
point (not urgent; for others, not us).
